dataset: full_merged
model: GRU_FCOV
gru_run_sig: "gru_l2_seed40_ep50_full_merged_spf0p8_sc20_ss42"
gp_run_tag: "gp_add_features_v1"
run_sig: auto
seed: 40
spatial_split_tag: ""
spatial_split_file: ""
max_pairs: 0

date_freq: "ME"
pretrain_steps: 300
pretrain_lr: 0.01
max_pretrain_pts: 2000

backend: "gpytorch"
kernel_type: "matern32"
isotropic: true
jitter: 0.00001
n_inducing: 64
variational_lr: 0.01
use_float64: true

gp_features:
  - gok
  - GW_recharge_r1000m
  - TWI_dgm50_r1000m
  - DSD_order1_r1000m
  - LP_order1_r1000m
  - SD_order1_r1000m
  - HGN_anthro
gp_features_onehot:
  - hydroraum

kernel:
  nu: 1.5
  length_scale: 1.0
  noise: 0.001
  restarts: 2
