apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gw-pred-rwx
  namespace: s91182
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: shared
