dataset: full_merged
kriging_source: "pred"
run_sig: "TFT_in52_out16_ep50_bs4096_stat1_seed40_full_merged"
horizon: 16
seed: 40
spatial_split_tag: ""
spatial_split_file: "" 
max_pairs: 0

date_strategy: "biweekly"
# date_strategy: "monthly"
# kriging_dates:
#   - "2021-04-19"
#   - "2021-05-03"

kernel:
  nu: 1.5
  length_scale: 1.0
  noise: 0.001
  restarts: 2
