dataset: full_merged
run_sig: auto
data:
  in_len: 52
  out_len: 16
  statics: true
model:
  gru_hidden: 256
  gru_layers: 4
  gru_dropout: 0.2
training:
  epochs: 50
  batch_size: 4096
  seed: 40
  num_workers: 10
  lr: 0.0002
  grad_clip: 1.0
  early_stopping:
    monitor: val_loss
    patience: 5
    min_delta: 0.0001
    mode: min
spatial_split:
  file: splits/spatial_split_full_merged_spf0p8_sc20_ss42.csv
